# Generated by Django 5.2.1 on 2026-06-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelroute',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('forming', '报名成团中'), ('completed', '已结束')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=60, verbose_name='评价人')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='评分')),
                ('feedback', models.TextField(blank=True, verbose_name='反馈内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='routes.travelroute')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
